services:
  postgres:
    container_name: fastfeet-pg
    image: postgres:16.0-alpine3.18
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: delivery
      PGDATA: ./data/postgres
    # volumes:
    # - ./data/pg:/data/postgres

  cache:
    container_name: fastfeet-redis
    image: redis
    privileged: true
    ports:
      - 6379:6379
    # volumes:
    #   - ./data/redis:/data
